FROM python:3.7-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r /usr/src/app/requirements.txt

COPY . /usr/src/app/

EXPOSE 8866

CMD ["gunicorn", "-w", "3", "-b", ":8866", "-t", "360", "--chdir", "/usr/src/app/src/main", "--reload", "api:app"]



FROM nginx:1.17.10
COPY nginx.conf /etc/nginx/nginx.conf
