FROM node:10.20-buster

WORKDIR /usr/src/web

ENV PATH /usr/src/web/node_modules/.bin:$PATH

COPY package.json /usr/src/web/package.json
COPY . /usr/src/web
RUN npm install -g @angular/cli@8.3.0
RUN npm install

CMD ng serve --host 0.0.0.0

